---
# tasks file for app_role

- name: create the deployments and services
  command:  kubectl apply -f -
  args:
      stdin: "{{ lookup('template', '{{ item }}-app.yaml.j2') }}"
  loop:
    - deployment
    - service
- name: Allow access to {{ NODE_PORT }} TCP port on GCP
  command: gcloud compute firewall-rules create rule-{{ NODE_PORT}} --allow=TCP:{{ NODE_PORT }}
